name = "sink-jiun"
compatibility_date = "2025-06-12"
compatibility_flags = [
  "nodejs_compat",
  # 二选一：是否自动注入 Dashboard 里的环境变量到 process.env
  "nodejs_compat_do_not_populate_process_env"
  # 或 "nodejs_compat_populate_process_env"
]
type = "javascript"

[build]
# 这一行告诉 Pages 你的输出目录在哪，否则会跳过整个配置
pages_build_output_dir = "dist"
